final List<Map<String, dynamic>> countryCodes = [
  {
    "e164_cc": "213",
    "iso2_cc": "DZ",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Algeria",
    "example": "551234567",
    "display_name": "Algeria (DZ) [+213]",
    "full_example_with_plus_sign": "+213551234567",
    "display_name_no_e164_cc": "Algeria (DZ)",
    "e164_key": "213-DZ-0",
    "cities": [
      "Algiers",
      "Annaba",
      "Azazga",
      "Batna City",
      "Blida",
      "Bordj",
      "Bordj Bou Arreridj",
      "Bougara",
      "Cheraga",
      "Chlef",
      "Constantine",
      "Djelfa",
      "Draria",
      "El Tarf",
      "Hussein Dey",
      "Illizi",
      "Jijel",
      "Kouba",
      "Laghouat",
      "Oran",
      "Ouargla",
      "Oued Smar",
      "Relizane",
      "Rouiba",
      "Saida",
      "Souk Ahras",
      "Tamanghasset",
      "Tiaret",
      "Tissemsilt",
      "Tizi",
      "Tizi Ouzou",
      "Tlemcen"
    ],
  },
  {
    "e164_cc": "244",
    "iso2_cc": "AO",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Angola",
    "example": "923123456",
    "display_name": "Angola (AO) [+244]",
    "full_example_with_plus_sign": "+244923123456",
    "display_name_no_e164_cc": "Angola (AO)",
    "e164_key": "244-AO-0",
    "cities": [
      "Ambriz",
      "Benguela",
      "Cabinda",
      "Cacole",
      "Camabatela",
      "Cazeta",
      "Huambo",
      "Kuito",
      "Lobito",
      "Luanda",
      "Lubango",
      "Lucapa",
      "Lumeje",
      "Malanje",
      "Menongue",
      "Muxaluando",
      "Namibe",
      "Ondjiva",
      "Piri",
      "Saurimo",
      "Talatona"
    ],
  },
  {
    "e164_cc": "229",
    "iso2_cc": "BJ",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Benin",
    "example": "90011234",
    "display_name": "Benin (BJ) [+229]",
    "full_example_with_plus_sign": "+22990011234",
    "display_name_no_e164_cc": "Benin (BJ)",
    "e164_key": "229-BJ-0",
    "cities": [
      "Abomey",
      "Allada",
      "Aplahoué",
      "Bohicon",
      "Boukombé",
      "Cotonou",
      "Dassa-Zoumé",
      "Djougou",
      "Ganvié",
      "Grand-Popo",
      "Kandi",
      "Kétou",
      "Kodomé",
      "Lokossa",
      "Malanville",
      "Natitingou",
      "Ouidah",
      "Parakou",
      "Porto-Novo",
      "Savé",
      "Ségbana",
      "Tanguiéta",
      "Tchaourou",
    ]
  },
  {
    "e164_cc": "267",
    "iso2_cc": "BW",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Botswana",
    "example": "71123456",
    "display_name": "Botswana (BW) [+267]",
    "full_example_with_plus_sign": "+26771123456",
    "display_name_no_e164_cc": "Botswana (BW)",
    "e164_key": "267-BW-0",
    "cities": [
      "Francistown",
      "Gaborone",
      "Orapa",
      "Serowe",
      "Village",
    ],
  },
  {
    "e164_cc": "226",
    "iso2_cc": "BF",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Burkina Faso",
    "example": "70123456",
    "display_name": "Burkina Faso (BF) [+226]",
    "full_example_with_plus_sign": "+22670123456",
    "display_name_no_e164_cc": "Burkina Faso (BF)",
    "e164_key": "226-BF-0",
    "cities": [
      "Banfora",
      "Bobo-Dioulasso",
      "Fada N'Gourma",
      "Kaya",
      "Koudougou",
      "Ouahigouya",
      "Ouagadougou",
    ]
  },
  {
    "e164_cc": "257",
    "iso2_cc": "BI",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Burundi",
    "example": "79561234",
    "display_name": "Burundi (BI) [+257]",
    "full_example_with_plus_sign": "+25779561234",
    "display_name_no_e164_cc": "Burundi (BI)",
    "e164_key": "257-BI-0",
    "cities": [
      "Bujumbura",
      "Gitega",
      "Muyinga",
      "Ngozi",
      "Ruyigi",
      "Makamba",
      "Cankuzo",
      "Kirundo",
      "Cibitoke",
      "Rutana",
    ],
  },
  {
    "e164_cc": "237",
    "iso2_cc": "CM",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Cameroon",
    "example": "71234567",
    "display_name": "Cameroon (CM) [+237]",
    "full_example_with_plus_sign": "+23771234567",
    "display_name_no_e164_cc": "Cameroon (CM)",
    "e164_key": "237-CM-0",
    "cities": [
      // "Bafia",
      // "Bafoussam",
      // "Bamenda",
      // "Buea",
      // "Douala",
      // "Kribi",
      // "Kumba",
      // "Tibati",
      // "Yaoundé",

      "Abong Mbang",
      "Akonolinga",
      "Ambam",
      "Bafia",
      "Bafoussam",
      "Bagangté",
      "Bali",
      "Bandjoun",
      "Bangangté",
      "Bamenda",
      "Bertoua",
      "Buea",
      "Douala",
      "Ebolowa",
      "Foumban",
      "Garoua",
      "Kribi",
      "Kumba",
      "Limbe",
      "Loum",
      "Maroua",
      "Mbalmayo",
      "Mbouda",
      "Meiganga",
      "Mokolo",
      "Mora",
      "Ngaoundéré",
      "Nkongsamba",
      "Nkoteng",
      "Sangmélima",
      "Tibati",
      "Tiko",
      "Touboro",
      "Yagoua",
      "Yaoundé",
      "Yokadouma"
    ],
  },
  {
    "e164_cc": "238",
    "iso2_cc": "CV",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Cape Verde",
    "example": "9911234",
    "display_name": "Cape Verde (CV) [+238]",
    "full_example_with_plus_sign": "+2389911234",
    "display_name_no_e164_cc": "Cape Verde (CV)",
    "e164_key": "238-CV-0",
    "cities": [
      "Praia",
      "Mindelo",
      "Santa Maria",
      "Espargos",
      "Assomada",
      "Pedra Badejo",
      "Tarrafal",
      "São Filipe",
      "Sal Rei",
      "Porto Novo",
    ]
  },
  {
    "e164_cc": "236",
    "iso2_cc": "CF",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Central African Republic",
    "example": "70012345",
    "display_name": "Central African Republic (CF) [+236]",
    "full_example_with_plus_sign": "+23670012345",
    "display_name_no_e164_cc": "Central African Republic (CF)",
    "e164_key": "236-CF-0",
    "cities": [
      "Alindao",
      "Baboua",
      "Bahamo",
      "Bambari",
      "Bangassou",
      "Bangui",
      "Baoro",
      "Batangafo",
      "Berbérati",
      "Bimbo",
      "Birao",
      "Boali",
      "Bobangui",
      "Boda",
      "Bossangoa",
      "Bossembélé",
      "Bouar",
      "Bouca",
      "Bozoum",
      "Bria",
      "Carnot",
      "Damara",
      "Gambo",
      "Gamboula",
      "Guen",
      "Ippy",
      "Kabo",
      "Kaga-Bandoro",
      "Kembé",
      "Kouango",
      "Mbaïki",
      "Mobaye",
      "Mongoumba",
      "N'Délé",
      "Nola",
      "Obo",
      "Ouadda",
      "Ouango",
      "Paoua",
      "Rafaï",
      "Sibut",
      "Zinga"
    ]
  },
  {
    "e164_cc": "235",
    "iso2_cc": "TD",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Chad",
    "example": "63012345",
    "display_name": "Chad (TD) [+235]",
    "full_example_with_plus_sign": "+23563012345",
    "display_name_no_e164_cc": "Chad (TD)",
    "e164_key": "235-TD-0",
    "cities": [
      "Abéché",
      "Am Timan",
      "Biltine",
      "Bogoro",
      "Bongor",
      "Doba",
      "Faya-Largeau",
      "Goré",
      "Iriba",
      "Kélo",
      "Koumra",
      "Moundou",
      "N'Djamena",
      "Oum Hadjer",
      "Pala",
      "Sarh",
      "Tinghir",
      "Zougra"
    ]
  },
  {
    "e164_cc": "269",
    "iso2_cc": "KM",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Comoros",
    "example": "3212345",
    "display_name": "Comoros (KM) [+269]",
    "full_example_with_plus_sign": "+2693212345",
    "display_name_no_e164_cc": "Comoros (KM)",
    "e164_key": "269-KM-0",
    "cities": [
      "Moroni",
      "Moutsamoudou",
      "Fomboni",
      "Tsingoni",
      "Domoni",
      "Bandrele",
      "Mitsamiouli",
      "Ziguinchor",
      "Idini",
      "Dzaoudzi",
    ],
  },
  {
    "e164_cc": "243",
    "iso2_cc": "CD",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Democratic Republic Congo",
    "example": "991234567",
    "display_name": "Democratic Republic Congo (CD) [+243]",
    "full_example_with_plus_sign": "+243991234567",
    "display_name_no_e164_cc": "Democratic Republic Congo (CD)",
    "e164_key": "243-CD-0",
    "cities": [
      "Banana",
      "Goma",
      "Kinshasa",
      "Likasi",
      "Lubumbashi",
    ],
  },
  {
    "e164_cc": "242",
    "iso2_cc": "CG",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Republic of Congo",
    "example": "061234567",
    "display_name": "Republic of Congo (CG) [+242]",
    "full_example_with_plus_sign": "+242061234567",
    "display_name_no_e164_cc": "Republic of Congo (CG)",
    "e164_key": "242-CG-0",
    "cities": [
      "Banana",
      "Goma",
      "Kinshasa",
      "Likasi",
      "Lubumbashi",
    ],
  },
  {
    "e164_cc": "225",
    "iso2_cc": "CI",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Côte d'Ivoire",
    "example": "01234567",
    "display_name": "Côte d'Ivoire (CI) [+225]",
    "full_example_with_plus_sign": "+22501234567",
    "display_name_no_e164_cc": "Côte d'Ivoire (CI)",
    "e164_key": "225-CI-0",
    "cities": [
      "Abidjan",
      "Abengourou",
      "Agboville",
      "Anyama",
      "Bingerville",
      "Bondoukou",
      "Bouaké",
      "Bouaflé",
      "Boundiali",
      "Dabou",
      "Danané",
      "Divo",
      "Gagnoa",
      "Guiglo",
      "Issia",
      "Korhogo",
      "Lakota",
      "Man",
      "Mankono",
      "Méagui",
      "Odienné",
      "Oumé",
      "Sassandra",
      "San-Pédro",
      "Séguéla",
      "Soubré",
      "Toumodi",
      "Tiassalé",
      "Touba",
      "Vavoua",
      "Yamoussoukro",
      "Zuénoula",
    ]
  },
  {
    "e164_cc": "253",
    "iso2_cc": "DJ",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Djibouti",
    "example": "77831001",
    "display_name": "Djibouti (DJ) [+253]",
    "full_example_with_plus_sign": "+25377831001",
    "display_name_no_e164_cc": "Djibouti (DJ)",
    "e164_key": "253-DJ-0",
    "cities": [
      "Djibouti City",
      "Ali Sabieh",
      "Dikhil",
      "Tadjourah",
      "Obock",
      "Arta",
      "Yoboki",
      "Randa",
      "Loyada",
      "Holhol",
    ],
  },
  {
    "e164_cc": "20",
    "iso2_cc": "EG",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Egypt",
    "example": "1001234567",
    "display_name": "Egypt (EG) [+20]",
    "full_example_with_plus_sign": "+201001234567",
    "display_name_no_e164_cc": "Egypt (EG)",
    "e164_key": "20-EG-0",
    "cities": [
      "Abu Hammad",
      "Al Mahallah al Kubra",
      "Al Mansurah",
      "Al Marj",
      "Alexandria",
      "Almazah",
      "Ar Rawdah",
      "Assiut",
      "Az Zamalik",
      "Badr",
      "Banha",
      "Bani Suwayf",
      "Cairo",
      "Damietta",
      "Faraskur",
      "Flaminj",
      "Giza",
      "Heliopolis",
      "Helwan",
      "Hurghada",
      "Ismailia",
      "Kafr ash Shaykh",
      "Luxor",
      "Madinat an Nasr",
      "Madinat as Sadis min Uktubar",
      "Minya",
      "Nasr",
      "New Cairo",
      "Port Said",
      "Rafah",
      "Ramsis",
      "Sadat",
      "Shirbin",
      "Shubra",
      "Sohag",
      "Suez",
      "Tanta",
      "Toukh",
      "Zagazig"
    ],
  },
  {
    "e164_cc": "240",
    "iso2_cc": "GQ",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Equatorial Guinea",
    "example": "222123456",
    "display_name": "Equatorial Guinea (GQ) [+240]",
    "full_example_with_plus_sign": "+240222123456",
    "display_name_no_e164_cc": "Equatorial Guinea (GQ)",
    "e164_key": "240-GQ-0",
    "cities": [
      "Acalayong",
      "Bata",
      "Ebebiyín",
      "Luba",
      "Mikomeseng",
      "Mongomo",
      "Rebola",
      "San Antonio de Palé",
      "Malabo",
    ]
  },
  {
    "e164_cc": "268",
    "iso2_cc": "SZ",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Eswatini",
    "example": "76123456",
    "display_name": "Eswatini (SZ) [+268]",
    "full_example_with_plus_sign": "+26876123456",
    "display_name_no_e164_cc": "Eswatini (SZ)",
    "e164_key": "268-SZ-0",
    "cities": [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
    ]
  },
  {
    "e164_cc": "251",
    "iso2_cc": "ET",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Ethiopia",
    "example": "911234567",
    "display_name": "Ethiopia (ET) [+251]",
    "full_example_with_plus_sign": "+251911234567",
    "display_name_no_e164_cc": "Ethiopia (ET)",
    "e164_key": "251-ET-0",
    "cities": [
      "Addis Ababa",
      "Dire Dawa",
      "Mekelle",
      "Adama",
      "Hawassa",
      "Bahir Dar",
      "Gonder",
      "Dessie",
      "Jimma",
      "Jijiga",
    ]
  },
  {
    "e164_cc": "241",
    "iso2_cc": "GA",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Gabon",
    "example": "06031234",
    "display_name": "Gabon (GA) [+241]",
    "full_example_with_plus_sign": "+24106031234",
    "display_name_no_e164_cc": "Gabon (GA)",
    "e164_key": "241-GA-0",
    "cities": [
      "Gamba",
      "Libreville",
      "Mamagnia",
      "Moanda",
      "Port-Gentil",
    ],
  },
  {
    "e164_cc": "220",
    "iso2_cc": "GM",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Gambia",
    "example": "3012345",
    "display_name": "Gambia (GM) [+220]",
    "full_example_with_plus_sign": "+2203012345",
    "display_name_no_e164_cc": "Gambia (GM)",
    "e164_key": "220-GM-0",
    "cities": [
      "Banjul",
      "Brikama",
      "Basse Santa Su",
      "Farafenni",
      "Serrekunda",
      "Bakau",
      "Sukuta",
      "Gunjur",
      "Soma",
      "Bansang",
    ]
  },
  {
    "e164_cc": "233",
    "iso2_cc": "GH",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Ghana",
    "example": "231234567",
    "display_name": "Ghana (GH) [+233]",
    "full_example_with_plus_sign": "+233231234567",
    "display_name_no_e164_cc": "Ghana (GH)",
    "e164_key": "233-GH-0",
    "cities": [
      "Accra",
      "Bawku",
      "Berekum",
      "Bolgatanga",
      "Cape Coast",
      "Home",
      "Koforidua",
      "Kumasi",
      "Legon",
      "Mampong",
      "Navrongo",
      "Sunyani",
      "Takoradi",
      "Tema",
      "Wa",
      "Winneba"
    ],
  },
  {
    "e164_cc": "224",
    "iso2_cc": "GN",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Guinea Conakry",
    "example": "60201234",
    "display_name": "Guinea Conakry (GN) [+224]",
    "full_example_with_plus_sign": "+22460201234",
    "display_name_no_e164_cc": "Guinea Conakry (GN)",
    "e164_key": "224-GN-0",
    "cities": [
      "Conakry",
      "Nzérékoré",
      "Kindia",
      "Boké",
      "Kankan",
      "Kissidougou",
      "Guéckédou",
      "Kamsar",
      "Mamou",
      "Macenta",
    ]
  },
  {
    "e164_cc": "245",
    "iso2_cc": "GW",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Guinea-Bissau",
    "example": "5012345",
    "display_name": "Guinea-Bissau (GW) [+245]",
    "full_example_with_plus_sign": "+2455012345",
    "display_name_no_e164_cc": "Guinea-Bissau (GW)",
    "e164_key": "245-GW-0",
    "cities": [
      "Bissau",
      "Bafatá",
      "Cacheu",
      "Gabu",
      "Buba",
      "Catió",
      "Mansôa",
      "Canchungo",
      "Quebo",
      "Quinhámel",
      "Farim",
      "Koundara",
    ]
  },
  {
    "e164_cc": "592",
    "iso2_cc": "GY",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Guyana",
    "example": "6091234",
    "display_name": "Guyana (GY) [+592]",
    "full_example_with_plus_sign": "+5926091234",
    "display_name_no_e164_cc": "Guyana (GY)",
    "e164_key": "592-GY-0",
    "cities": [
      "Anna Regina",
      "Bartica",
      "Corriverton",
      "Georgetown",
      "Lethem",
      "Linden",
      "Mabaruma",
      "New Amsterdam",
      "Rose Hall",
    ]
  },
  {
    "e164_cc": "254",
    "iso2_cc": "KE",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Kenya",
    "example": "712123456",
    "display_name": "Kenya (KE) [+254]",
    "full_example_with_plus_sign": "+254712123456",
    "display_name_no_e164_cc": "Kenya (KE)",
    "e164_key": "254-KE-0",
    "cities": [
      "Bondo",
      "Chuka",
      "Eldoret",
      "Kabete",
      "Kaiboi",
      "Karatina",
      "Kiambu",
      "Kikuyu",
      "Kisii",
      "Kisumu",
      "Kitale",
      "Kitui",
      "Machakos",
      "Maseno",
      "Mbita",
      "Mombasa",
      "Nairobi",
      "Nakuru",
      "Sawa Sawa",
      "Siaya",
      "Thika",
      "Turbo",
      "Wote"
    ],
  },
  {
    "e164_cc": "266",
    "iso2_cc": "LS",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Lesotho",
    "example": "50123456",
    "display_name": "Lesotho (LS) [+266]",
    "full_example_with_plus_sign": "+26650123456",
    "display_name_no_e164_cc": "Lesotho (LS)",
    "e164_key": "266-LS-0",
    "cities": [
      "Maseru",
      "Mohale's Hoek",
      "Mafeteng",
      "Hlotse",
      "Maputsoe",
      "Teyateyaneng",
      "Butha-Buthe",
      "Qacha's Nek",
      "Quthing",
      "Mokhotlong",
    ]
  },
  {
    "e164_cc": "231",
    "iso2_cc": "LR",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Liberia",
    "example": "4612345",
    "display_name": "Liberia (LR) [+231]",
    "full_example_with_plus_sign": "+2314612345",
    "display_name_no_e164_cc": "Liberia (LR)",
    "e164_key": "231-LR-0",
    "cities": [
      "Monrovia",
      "Ganta",
      "Gbarnga",
      "Buchanan",
      "Harper",
      "Kakata",
      "Paynesville",
      "Bong Mines",
      "New Kru Town",
      "Upper Buchanan",
    ]
  },
  {
    "e164_cc": "218",
    "iso2_cc": "LY",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Libya",
    "example": "912345678",
    "display_name": "Libya (LY) [+218]",
    "full_example_with_plus_sign": "+218912345678",
    "display_name_no_e164_cc": "Libya (LY)",
    "e164_key": "218-LY-0",
    "cities": [
      "Benghazi",
      "Misratah",
      "Sabha",
      "Tripoli",
      "Zliten",
    ],
  },
  {
    "e164_cc": "261",
    "iso2_cc": "MG",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Madagascar",
    "example": "301234567",
    "display_name": "Madagascar (MG) [+261]",
    "full_example_with_plus_sign": "+261301234567",
    "display_name_no_e164_cc": "Madagascar (MG)",
    "e164_key": "261-MG-0",
    "cities": [
      "Ambanja",
      "Antananarivo",
      "Antsirabe",
      "Antsiranana",
      "Fianarantsoa",
      "Toamasina",
      "Toliara"
    ],
  },
  {
    "e164_cc": "265",
    "iso2_cc": "MW",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Malawi",
    "example": "991234567",
    "display_name": "Malawi (MW) [+265]",
    "full_example_with_plus_sign": "+265991234567",
    "display_name_no_e164_cc": "Malawi (MW)",
    "e164_key": "265-MW-0",
    "cities": [
      "Lilongwe",
      "Blantyre",
      "Mzuzu",
      "Zomba",
      "Karonga",
      "Kasungu",
      "Mangochi",
      "Salima",
      "Liwonde",
      "Balaka",
    ]
  },
  {
    "e164_cc": "223",
    "iso2_cc": "ML",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Mali",
    "example": "65012345",
    "display_name": "Mali (ML) [+223]",
    "full_example_with_plus_sign": "+22365012345",
    "display_name_no_e164_cc": "Mali (ML)",
    "e164_key": "223-ML-0",
    "cities": [
      "Bamako",
      "Sikasso",
      "Koulikoro",
      "Mopti",
      "Gao",
      "Kayes",
      "Kidal",
      "Tombouctou",
      "Ségou",
      "Kati",
    ]
  },
  {
    "e164_cc": "222",
    "iso2_cc": "MR",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Mauritania",
    "example": "22123456",
    "display_name": "Mauritania (MR) [+222]",
    "full_example_with_plus_sign": "+22222123456",
    "display_name_no_e164_cc": "Mauritania (MR)",
    "e164_key": "222-MR-0",
    "cities": [
      "Nouakchott",
      "Nouadhibou",
      "Kiffa",
      "Mbera Refugee Camp",
      "Kaédi",
      "Zouérat",
      "Rosso",
      "Sélibabi",
      "Boû Gâdoûm",
      "Boutilimit",
    ]
  },
  {
    "e164_cc": "230",
    "iso2_cc": "MU",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Mauritius",
    "example": "2512345",
    "display_name": "Mauritius (MU) [+230]",
    "full_example_with_plus_sign": "+2302512345",
    "display_name_no_e164_cc": "Mauritius (MU)",
    "e164_key": "230-MU-0",
    "cities": [
      "Beau Bassin",
      "Chemin Grenier",
      "Ebene CyberCity",
      "Floreal",
      "Goodlands",
      "Le Reduit",
      "Port Louis",
      "Port Mathurin",
      "Quatre Bornes",
      "Rose Hill",
      "Saint Jean",
      "Tamarin",
      "Vacoas"
    ],
  },
  {
    "e164_cc": "212",
    "iso2_cc": "MA",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Morocco",
    "example": "650123456",
    "display_name": "Morocco (MA) [+212]",
    "full_example_with_plus_sign": "+212650123456",
    "display_name_no_e164_cc": "Morocco (MA)",
    "e164_key": "212-MA-0",
    "cities": [
      "Afourer",
      "Agadir",
      "Ait Melloul",
      "Al Hoceima",
      "Assa",
      "Benguerir",
      "Beni Mellal",
      "Berrechid",
      "Casablanca",
      "Deroua",
      "El Gara",
      "El Hajeb",
      "El Jadida",
      "Erfoud",
      "Fes",
      "Fkih Ben Salah",
      "Kenitra",
      "Khemisset",
      "Khouribga",
      "Ksar el Kebir",
      "Larache",
      "Mansour",
      "Marrakesh",
      "Mehediyah",
      "Meknes",
      "Mohammedia",
      "Nador",
      "Ouazzane",
      "Oued Zem",
      "Oujda",
      "Oulad Teima",
      "Rabat",
      "Safi",
      "Sefrou",
      "Settat",
      "Sidi Bennour",
      "Sidi Slimane",
      "Skhirat",
      "Tahala",
      "Tan-Tan",
      "Tangier",
      "Tarfaya",
      "Taza",
      "Temara",
      "Tiflet",
      "Tiznit",
      "Touissite"
    ],
  },
  {
    "e164_cc": "258",
    "iso2_cc": "MZ",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Mozambique",
    "example": "821234567",
    "display_name": "Mozambique (MZ) [+258]",
    "full_example_with_plus_sign": "+258821234567",
    "display_name_no_e164_cc": "Mozambique (MZ)",
    "e164_key": "258-MZ-0",
    "cities": [
      "Beira",
      "Maputo",
      "Matola",
      "Mozambique",
      "Nampula",
      "Pemba",
      "Quelimane",
      "Tete"
    ],
  },
  {
    "e164_cc": "264",
    "iso2_cc": "NA",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Namibia",
    "example": "811234567",
    "display_name": "Namibia (NA) [+264]",
    "full_example_with_plus_sign": "+264811234567",
    "display_name_no_e164_cc": "Namibia (NA)",
    "e164_key": "264-NA-0",
    "cities": [
      "Etunda",
      "Grootfontein",
      "Katima Mulilo",
      "Keetmanshoop",
      "Mpapuka",
      "Olympia",
      "Ondangwa",
      "Ongwediva",
      "Oranjemund",
      "Oshakati",
      "Otjiwarongo",
      "Outapi",
      "Swakopmund",
      "Tsumeb",
      "Walvis Bay",
      "Windhoek"
    ],
  },
  {
    "e164_cc": "227",
    "iso2_cc": "NE",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Niger",
    "example": "93123456",
    "display_name": "Niger (NE) [+227]",
    "full_example_with_plus_sign": "+22793123456",
    "display_name_no_e164_cc": "Niger (NE)",
    "e164_key": "227-NE-0",
    "cities": [
      "Anna Regina",
      "Bartica",
      "Corriverton",
      "Georgetown",
      "Lethem",
      "Linden",
      "Mabaruma",
      "New Amsterdam",
      "Rose Hall",
    ]
  },
  {
    "e164_cc": "234",
    "iso2_cc": "NG",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Nigeria",
    "example": "8021234567",
    "display_name": "Nigeria (NG) [+234]",
    "full_example_with_plus_sign": "+2348021234567",
    "display_name_no_e164_cc": "Nigeria (NG)",
    "e164_key": "234-NG-0",
    "cities": [
      "Aba",
      "Abakaliki",
      "Abeokuta",
      "Abraka",
      "Abraka",
      "Abuja",
      "Ado-Ekiti",
      "Adodo",
      "Aganga",
      "Agege",
      "Agidingbi",
      "Ajegunle",
      "Ajuwon",
      "Akure",
      "Alimosho",
      "Anambra",
      "Apapa",
      "Ayobo",
      "Benin City",
      "Birnin Kebbi",
      "Bonny",
      "Burutu",
      "Bwari",
      "Calabar",
      "Chafe",
      "Damaturu",
      "Egbeda",
      "Ekpoma",
      "Enugu",
      "Forum",
      "Funtua",
      "Ibadan",
      "Ido",
      "Ifako",
      "Igando",
      "Igueben",
      "Ikeja",
      "Ikorodu",
      "Ikotun",
      "Ile-Ife",
      "Ilesa",
      "Ilorin",
      "Ipaja",
      "Iseri-Oke",
      "Isolo",
      "Jalingo",
      "Jos",
      "Kaduna",
      "Kano",
      "Kebbi",
      "Lagos",
      "Lekki",
      "Lokoja",
      "Magodo",
      "Makurdi",
      "Maryland",
      "Minna",
      "Mogho",
      "Mowe",
      "Mushin",
      "Nsukka",
      "Obafemi",
      "Obudu",
      "Odau",
      "Ojo",
      "Ojota",
      "Ondo",
      "Onigbongbo",
      "Orile Oshodi",
      "Oshodi",
      "Osogbo",
      "Ota",
      "Owerri",
      "Oworonsoki",
      "Port Harcourt",
      "Shomolu",
      "Suleja",
      "Suru-Lere",
      "Tara",
      "Ughelli",
      "Ungwan Madaki",
      "Uyo",
      "Warri",
      "Warri",
      "Yaba",
      "Yola",
      "Zaria"
    ],
  },
  {
    "e164_cc": "250",
    "iso2_cc": "RW",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Rwanda",
    "example": "720123456",
    "display_name": "Rwanda (RW) [+250]",
    "full_example_with_plus_sign": "+250720123456",
    "display_name_no_e164_cc": "Rwanda (RW)",
    "e164_key": "250-RW-0",
    "cities": [
      "Kigali",
      "Gisenyi",
      "Butare",
      "Gitarama",
      "Ruhengeri",
      "Byumba",
      "Cyangugu",
      "Kibuye",
      "Rwamagana",
      "Kibungo",
    ]
  },
  {
    "e164_cc": "378",
    "iso2_cc": "SM",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "San Marino",
    "example": "66661212",
    "display_name": "San Marino (SM) [+378]",
    "full_example_with_plus_sign": "+37866661212",
    "display_name_no_e164_cc": "San Marino (SM)",
    "e164_key": "378-SM-0",
    "cities": [
      "Acquaviva",
      "Falciano",
      "Fiorentino",
      "San Marino",
      "Serravalle",
    ],
  },
  {
    "e164_cc": "239",
    "iso2_cc": "ST",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "São Tomé and Príncipe",
    "example": "9812345",
    "display_name": "São Tomé and Príncipe (ST) [+239]",
    "full_example_with_plus_sign": "+2399812345",
    "display_name_no_e164_cc": "São Tomé and Príncipe (ST)",
    "e164_key": "239-ST-0",
    "cities": [
      "São Tomé",
      "Neves",
      "Santo António",
      "Santa Cruz",
      "Pantufo",
      "Guadalupe",
      "Santo Amaro",
      "Trindade",
      "Santana",
      "Cantagalo",
    ]
  },
  {
    "e164_cc": "221",
    "iso2_cc": "SN",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Senegal",
    "example": "701012345",
    "display_name": "Senegal (SN) [+221]",
    "full_example_with_plus_sign": "+221701012345",
    "display_name_no_e164_cc": "Senegal (SN)",
    "e164_key": "221-SN-0",
    "cities": [
      "Boussinki",
      "Camberene",
      "Dakar",
      "Dodji",
      "Guediawaye",
      "Kaolack",
      "Kedougou",
      "Louga",
      "Madina Kokoun",
      "Saint-Louis",
      "Sama",
      "Tanaf"
    ],
  },
  {
    "e164_cc": "248",
    "iso2_cc": "SC",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Seychelles",
    "example": "2510123",
    "display_name": "Seychelles (SC) [+248]",
    "full_example_with_plus_sign": "+2482510123",
    "display_name_no_e164_cc": "Seychelles (SC)",
    "e164_key": "248-SC-0",
    "cities": [
      "Victoria",
      "Beau Vallon",
      "Anse Boileau",
      "Takamaka",
      "Grand Anse Mahe",
    ]
  },
  {
    "e164_cc": "232",
    "iso2_cc": "SL",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Sierra Leone",
    "example": "25123456",
    "display_name": "Sierra Leone (SL) [+232]",
    "full_example_with_plus_sign": "+23225123456",
    "display_name_no_e164_cc": "Sierra Leone (SL)",
    "e164_key": "232-SL-0",
    "cities": [
      "Freetown",
      "Bo",
      "Kenema",
      "Makeni",
      "Port Loko",
      "Magburaka",
      "Kailahun",
      "Pujehun",
      "Bonthe",
      "Tonkolili",
    ]
  },
  {
    "e164_cc": "27",
    "iso2_cc": "ZA",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "South Africa",
    "example": "711234567",
    "display_name": "South Africa (ZA) [+27]",
    "full_example_with_plus_sign": "+27711234567",
    "display_name_no_e164_cc": "South Africa (ZA)",
    "e164_key": "27-ZA-0",
    "cities": [
      "Alberton",
      "Alice",
      "Alrode",
      "Amanzimtoti",
      "Ashton",
      "Atlantis",
      "Balfour",
      "Bathurst",
      "Beaufort West",
      "Bedfordview",
      "Belhar",
      "Bellville",
      "Benoni",
      "Bergvliet",
      "Bethal",
      "Bethlehem",
      "Bloemfontein",
      "Boksburg",
      "Bothasig",
      "Botshabelo",
      "Braamfontein",
      "Brackenfell",
      "Brakpan",
      "Bredasdorp",
      "Brits",
      "Bronkhorstspruit",
      "Brooklyn",
      "Bryanston",
      "Buffalo",
      "Butterworth",
      "Cape Town",
      "Capital Park",
      "Carletonville",
      "Carolina",
      "Centurion",
      "City of Cape Town",
      "Clanwilliam",
      "Claremont",
      "Coega",
      "Coligny",
      "Constantia",
      "Craighall",
      "Cullinan",
      "De Aar",
      "Delmas",
      "Deneysville",
      "Despatch",
      "Doornfontein",
      "Dube Location",
      "Duiwelskloof",
      "Dullstroom",
      "Dundee",
      "Durban",
      "Durbanville",
      "East London",
      "Edenburg",
      "Edenvale",
      "Eersterivier",
      "Elandsfontein",
      "Elarduspark",
      "Eloff",
      "Elsburg",
      "Elsenburg",
      "Emerald Hill",
      "Emnambithi-Ladysmith",
      "Empangeni",
      "Erasmia",
      "Ermelo",
      "Eshowe",
      "Evander",
      "Faure",
      "Florida Glen",
      "Fochville",
      "Fordsburg",
      "Fort Cox",
      "Franschhoek",
      "Gansbaai",
      "Ganspan",
      "George",
      "Germiston",
      "Gezina",
      "Gillitts",
      "Gingindlovu",
      "Glen Austin",
      "Goodwood",
      "Graaff Reinet",
      "Grabouw",
      "Grahamstown",
      "Greytown",
      "Groblersdal",
      "Haenertsburg",
      "Harrismith",
      "Hartbeespoort",
      "Hartenbos",
      "Hartswater",
      "Hatfield",
      "Hawston",
      "Hazyview",
      "Heidelberg",
      "Hekpoort",
      "Henley on Klip",
      "Hennenman",
      "Hermanus",
      "Hillcrest",
      "Hilton",
      "Himeville",
      "Hluhluwe",
      "Hoedspruit",
      "Hogsback",
      "Houghton Estate",
      "Hout Bay",
      "Howick",
      "Humansdorp",
      "Hyde Park",
      "Irene",
      "Isando",
      "Ixopo",
      "Johannesburg",
      "Kalkbaai",
      "Katlehong",
      "Kempton Park",
      "Kimberley",
      "Kingsborough",
      "Kingsley",
      "Kingsmead",
      "Kinross",
      "Kleinmond",
      "Klerksdorp",
      "Kloof",
      "Knysna",
      "Kokstad",
      "Kraaifontein",
      "Kranskop",
      "Kriel",
      "Kroonstad",
      "Krugersdorp",
      "Kuils River",
      "KwaDukuza",
      "La Lucia",
      "La Motte",
      "Ladybrand",
      "Lansdowne",
      "Laudium",
      "Lephalale",
      "Lichtenburg",
      "Lombardy East",
      "London",
      "Louis Trichardt",
      "Lutzville",
      "Lydenburg",
      "Lyndhurst",
      "Lynnwood",
      "Lyttelton",
      "Machadodorp",
      "Mafikeng",
      "Maidstone",
      "Majuba",
      "Malmesbury",
      "Malvern",
      "Maraisburg",
      "Margate",
      "Marshalltown",
      "Meadowridge",
      "Medunsa",
      "Melkbosstrand",
      "Merrivale",
      "Messina",
      "Meyerton",
      "Middelburg",
      "Middelburg",
      "Midrand",
      "Milnerton",
      "Mmabatho",
      "Mobeni",
      "Modderfontein",
      "Mokopane",
      "Montagu",
      "Monument Park",
      "Mooi River",
      "Mookgophong",
      "Moorreesburg",
      "Morningside Manor",
      "Mossel Bay",
      "Mount Edgecombe",
      "Mthatha",
      "Muizenberg",
      "Napier",
      "Nelspruit",
      "New Germany",
      "Newcastle",
      "Newlands",
      "Nigel",
      "Northcliff",
      "Odendaalsrus",
      "Ogies",
      "Olifantsfontein",
      "Onderstepoort",
      "Onverwacht",
      "Oranjeville",
      "Oranjezicht",
      "Ottosdal",
      "Oudtshoorn",
      "Overport",
      "Paarl",
      "Panorama",
      "Parktown",
      "Parkview",
      "Parow",
      "Peninsula",
      "Phalaborwa",
      "Philadelphia",
      "Philipstown",
      "Phoenix",
      "Phokeng",
      "Pietermaritzburg",
      "Pinelands",
      "Pinetown",
      "Plettenberg Bay",
      "Plumstead",
      "Polokwane",
      "Pongola",
      "Port Alfred",
      "Port Elizabeth",
      "Port Shepstone",
      "Potchefstroom",
      "Pretoria",
      "Prieska",
      "Primrose",
      "Pringle Bay",
      "Queensburgh",
      "Queenstown",
      "Queenswood",
      "Randburg",
      "Randfontein",
      "Rawsonville",
      "Rhodes",
      "Richards Bay",
      "Richmond",
      "Riebeek-Kasteel",
      "Rivonia",
      "Roggebaai",
      "Roodepoort",
      "Rooigrond",
      "Rooihuiskraal",
      "Rosebank",
      "Rosettenville",
      "Rosslyn",
      "Rustenburg",
      "Sabie",
      "Saint Helena Bay",
      "Saint James",
      "Saldanha",
      "Salt Rock",
      "Sandown",
      "Sandton",
      "Sasolburg",
      "Schweizer-Reneke",
      "Scottburgh",
      "Sebokeng",
      "Secunda",
      "Sedgefield",
      "Senekal",
      "Shelly Beach",
      "Silverton",
      "Sinoville",
      "Somerset West",
      "Soshanguve",
      "Soweto",
      "Springs",
      "Standerton",
      "Stanford",
      "Stellenbosch",
      "Stilfontein",
      "Strand",
      "Sun Valley",
      "Swartkops",
      "Temba",
      "Tembisa",
      "Thabazimbi",
      "The Rest",
      "Thohoyandou",
      "Three Anchor Bay",
      "Three Rivers",
      "Tokai",
      "Tongaat",
      "Tzaneen",
      "Uitenhage",
      "Umbogintwini",
      "Umdloti",
      "Umhlanga",
      "Umkomaas",
      "Umtentweni",
      "Upington",
      "Vaalbank",
      "Vaalpark",
      "Vanderbijlpark",
      "Vereeniging",
      "Verulam",
      "Villiersdorp",
      "Virginia",
      "Vosloorus",
      "Vrededorp",
      "Vredenburg",
      "Vryheid",
      "Walkerville",
      "Walmer Heights",
      "Warner Beach",
      "Wartburg",
      "Waverley",
      "Waverley",
      "Welgelegen",
      "Welgemoed",
      "Welkom",
      "Welkom",
      "Wellington",
      "Weltevreden",
      "Weltevreedenpark",
      "Westonaria",
      "Westville",
      "White River",
      "Wilderness",
      "Winterton",
      "Witbank",
      "Witpoortjie",
      "Wonderboom",
      "Worcester",
      "Wynberg",
      "Zeerust"
    ],
  },
  {
    "e164_cc": "211",
    "iso2_cc": "SS",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "South Sudan",
    "example": "977123456",
    "display_name": "South Sudan (SS) [+211]",
    "full_example_with_plus_sign": "+211977123456",
    "display_name_no_e164_cc": "South Sudan (SS)",
    "e164_key": "211-SS-0",
    "cities": [
      "Juba",
      "Malakal",
      "Wau",
      "Bor",
      "Yambio",
      "Rumbek",
      "Yei",
      "Bentiu",
      "Gogrial",
      "Torit",
    ]
  },
  {
    "e164_cc": "249",
    "iso2_cc": "SD",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Sudan",
    "example": "911231234",
    "display_name": "Sudan (SD) [+249]",
    "full_example_with_plus_sign": "+249911231234",
    "display_name_no_e164_cc": "Sudan (SD)",
    "e164_key": "249-SD-0",
    "cities": [
      "Kassala",
      "Khartoum",
      "Nyala",
      "Shendi",
      "Thabit",
      "Umm Durman"
    ],
  },
  {
    "e164_cc": "255",
    "iso2_cc": "TZ",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Tanzania",
    "example": "612345678",
    "display_name": "Tanzania (TZ) [+255]",
    "full_example_with_plus_sign": "+255612345678",
    "display_name_no_e164_cc": "Tanzania (TZ)",
    "e164_key": "255-TZ-0",
    "cities": [
      "Arusha",
      "Bukoba",
      "Dar es Salaam",
      "Dodoma",
      "Morogoro",
      "Mwanza",
      "Njombe",
      "Raha",
      "Tanga",
      "Zanzibar"
    ],
  },
  {
    "e164_cc": "228",
    "iso2_cc": "TG",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Togo",
    "example": "90112345",
    "display_name": "Togo (TG) [+228]",
    "full_example_with_plus_sign": "+22890112345",
    "display_name_no_e164_cc": "Togo (TG)",
    "e164_key": "228-TG-0",
    "cities": [
      "Lomé",
      "Sokodé",
      "Kara",
      "Kpalimé",
      "Atakpamé",
      "Bassar",
      "Tsévié",
      "Aného",
      "Mango",
      "Dapaong",
    ]
  },
  {
    "e164_cc": "216",
    "iso2_cc": "TN",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Tunisia",
    "example": "20123456",
    "display_name": "Tunisia (TN) [+216]",
    "full_example_with_plus_sign": "+21620123456",
    "display_name_no_e164_cc": "Tunisia (TN)",
    "e164_key": "216-TN-0",
    "cities": [
      "Ariana",
      "Beja",
      "Gafsa",
      "Hammamet",
      "Le Bardo",
      "Manouba",
      "Monastir",
      "Rades",
      "Sfax",
      "Sidi Bouzid",
      "Sousse",
      "Tunis"
    ],
  },
  {
    "e164_cc": "256",
    "iso2_cc": "UG",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Uganda",
    "example": "712345678",
    "display_name": "Uganda (UG) [+256]",
    "full_example_with_plus_sign": "+256712345678",
    "display_name_no_e164_cc": "Uganda (UG)",
    "e164_key": "256-UG-0",
    "cities": [
      "Kampala",
      "Gulu",
      "Lira",
      "Mbarara",
      "Jinja",
      "Arua",
      "Hoima",
      "Mukono",
      "Fort Portal",
      "Soroti"
    ]
  },
  {
    "e164_cc": "260",
    "iso2_cc": "ZM",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Zambia",
    "example": "955123456",
    "display_name": "Zambia (ZM) [+260]",
    "full_example_with_plus_sign": "+260955123456",
    "display_name_no_e164_cc": "Zambia (ZM)",
    "e164_key": "260-ZM-0",
    "cities": [
      "Kalomo",
      "Kitwe",
      "Livingstone",
      "Lusaka",
      "Macha",
      "Mumbwa",
      "Ndola",
      "Siavonga",
      "Solwezi"
    ],
  },
  {
    "e164_cc": "263",
    "iso2_cc": "ZW",
    "e164_sc": 0,
    "geographic": true,
    "level": 1,
    "name": "Zimbabwe",
    "example": "711234567",
    "display_name": "Zimbabwe (ZW) [+263]",
    "full_example_with_plus_sign": "+263711234567",
    "display_name_no_e164_cc": "Zimbabwe (ZW)",
    "e164_key": "263-ZW-0",
    "cities": [
      "Bulawayo",
      "Chinhoyi",
      "Greendale",
      "Gwanda",
      "Harare",
      "Kwekwe",
      "Mufakose",
      "Mutare",
      "Victoria Falls"
    ]
  }
];
